### ISSUE TITLE
Burden Does Not Take Into Account Backpack/Sack

### ISSUE THREAD

**Issue by dogggs** [neilbenson/foundryvtt-whitehack-3e#2]
When managing the inventory, one is not able to put items into the backpack, and the additional five slots granted by the backpack. One of my characters has total burden of 14.21 (five of which would be stored in a backpack) and it says "Massive burden".

**Comment by neilbenson** [comment]
Items can be either stored (in a backpack) or equipped, you switch between the two for each item. The massive burden of encumbrance 14.21 in equipped is correct, you should be able to put the 4.21 (or some combination) into stored. In this example the splint mail and shield are equipped and the helmet is stored. Hope that makes sense.

![image](https://user-images.githubusercontent.com/20140689/150215746-35780c18-9a5d-4dbf-b562-42f57809661c.png)

**Comment by dogggs** [comment]
Ah, okay, that does make sense. The source of my confusion was that "equipped" made me think it only applied to items that you could wear on the body, like weapons and armor. I didn't realize it also applied to anything stored outside the bags or backpacks. My mistake.
