### ISSUE TITLE
Enhancement: Arbitrary Damage

### ISSUE THREAD

**Issue by tuirgin** [neilbenson/foundryvtt-whitehack-3e#9]
Being able to specify arbitrary damage would be helpful for homebrew use cases. As an example use-case, take Milton's [*Running Whitehack like OD&D* article](https://the-last-redoubt.blogspot.com/2021/05/od.html) regarding Monster damage:

> ### Monsters
> 
> At the Referee's discretion, monsters may be subject to bonus damage if they are notably large, strong, deadly, or some combination of the three.
> 
> - Most monsters deal **1-6 damage**.
> - Notably strong monsters deal **2-7 damage**.
> - Inhumanly strong or large monsters, such as ogres, deal **3-8 damage**.
> - Supernaturally strong or giant monsters, such as balrogs or giants, deal **2-12 damage**.
> - Impossibly strong or massive monsters, such as titans or leviathans, deal **3-18 damage**.

**Comment by neilbenson** [comment]
Thanks for your feedback, these are good ideas. I've recently started a new job and don't have as much time to work on the Whitehack system but when I do I'll take a look at your suggestions.

**Comment by tuirgin** [comment]
Sure thing... this will do, really: 
![image](https://user-images.githubusercontent.com/97160/166168682-6f7d0ab2-e9ab-49f6-b1a2-02622740fe60.png)

I may actually see if I can scratch my own itch. I'm no web developer, but I write test automation code in Python on a daily basis.

**Comment by neilbenson** [comment]
Apologies for not replying sooner. That seems like a good solution... wish I had more time to resolve these issues as they all make sense to me.

**Comment by neilbenson** [comment]
In the upcoming v10 release I've added more dice rolling options, so it goes 1, 1d6-2, 1d6-1, 1d6, 1d6+1, 1d6+2, 1d6+3, 1d6+4... then the same for 2d6 and 3d6. Hopefully that will give you all the options you need.
